AWSTemplateFormatVersion: 2010-09-09
Description: LAMP with AutoScaling and ALB
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  myVPC:
    Description: vpcid
    Type: 'AWS::EC2::VPC::Id'
  DBName:
    Default: myDatabase
    Description: MySQL database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBUser:
    NoEcho: 'true'
    Description: Username for MySQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password for MySQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  DBAllocatedStorage:
    Default: '5'
    Description: The size of the database (Gb)
    Type: Number
    MinValue: '5'
    MaxValue: '1024'
    ConstraintDescription: must be between 5 and 1024Gb.
  DBInstanceClass:
    Description: The database instance type
    Type: String
    Default: db.t2.micro
    AllowedValues:
      - db.t2.micro  
  MultiAZDatabase:
    Default: 'true'
    Description: Create a Multi-AZ MySQL Amazon RDS database instance
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    ConstraintDescription: must be either true or false.
Resources: 
  DBEC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Open database for access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          CidrIp: 0.0.0.0/0
      VpcId: !Ref myVPC

  MySQLDatabase:
      Type: 'AWS::RDS::DBInstance'
      Properties:
          Engine: MySQL
          DBName: !Ref DBName
          MultiAZ: !Ref MultiAZDatabase
          MasterUsername: !Ref DBUser
          MasterUserPassword: !Ref DBPassword
          DBInstanceClass: !Ref DBInstanceClass
          AllocatedStorage: !Ref DBAllocatedStorage
          VPCSecurityGroups:
            - !GetAtt 
              - DBEC2SecurityGroup
              - GroupId
Outputs:
  DBEndpoint:
    Description: RDS Endpoint URL
    Value: !GetAtt MySQLDatabase.Endpoint.Address

